baseURL = "https://www.jamesrampton.uk/"
languageCode = "en-us"
title = "James Rampton"

[author]
    name = "James Rampton"

[markup]
    [markup.highlight]
        noClasses = false

[imaging.exif]
includeFields = ".*"
