baseURL = "https://www.jamesrampton.uk/"
languageCode = "en-us"
title = "James Rampton"
rssLimit = 20
enableEmoji = true

[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[author]
    name = "James Rampton"

[markup]
    [markup.highlight]
        noClasses = false

[imaging.exif]
includeFields = ".*"
