description = "The personal website and blog of James Rampton"
noSEO = false
githubHistoryBaseURL = "https://github.com/jamesrampton/jamesrampton.uk/commits/main/content/"

[[social]]
name = "Github"
icon = "github"
order = 1
url = "https://github.com/jamesrampton"

[[social]]
name = "Mastodon"
icon = "mastodon"
order = 2
url = "https://jhr.social/@james"

[[social]]
name = "RSS"
icon = "rss"
order = 6
url = "/feed.xml"
