description = "The personal website and blog of James Rampton"
noSEO = false
githubHistoryBaseURL = "https://github.com/jamesrampton/jamesrampton.uk/commits/main/content/"

[[social]]
    name = "Github"
    icon = "github"
    order = 1
    url = "//github.com/jamesrampton"

[[social]]
    name = "Bandcamp"
    icon = "bandcamp"
    order = 2
    url = "//jamesrampton.bandcamp.com"

[[social]]
    name = "500px"
    icon = "500px"
    order = 3
    url = "//500px.com/p/jamesrampton"

[[social]]
    name = "Vimeo"
    icon = "vimeo"
    order = 4
    url = "//vimeo.com/jamesrampton"

[[social]]
    name = "RSS"
    icon = "rss"
    order = 5
    url = "/feed.xml"
