description = "The personal website and blog of James Rampton"
noSEO = false
githubHistoryBaseURL = "https://github.com/jamesrampton/jamesrampton.uk/commits/main/content/"

[[social]]
    name = "Github"
    icon = "github"
    order = 1
    url = "//github.com/jamesrampton"

[[social]]
    name = "Flickr"
    icon = "flickr"
    order = 2
    url = "//flickr.com/jamesrampton"

[[social]]
    name = "Vimeo"
    icon = "vimeo"
    order = 3
    url = "//vimeo.com/jamesrampton"

[[social]]
    name = "Bandcamp"
    icon = "bandcamp"
    order = 4
    url = "//jamesrampton.bandcamp.com"
