description = "The personal website and blog of James Rampton"
noSEO = false
githubHistoryBaseURL = "https://github.com/jamesrampton/jamesrampton.uk/commits/main/content/"

[[social]]
name = "Github"
icon = "github"
order = 1
url = "https://github.com/jamesrampton"

[[social]]
name = "Mastodon"
icon = "mastodon"
order = 2
url = "https://jhr.social/@james"

[[social]]
name = "Bandcamp"
icon = "bandcamp"
order = 3
url = "https://jamesrampton.bandcamp.com"

[[social]]
name = "500px"
icon = "500px"
order = 4
url = "https://500px.com/p/jamesrampton"

[[social]]
name = "Vimeo"
icon = "vimeo"
order = 5
url = "https://vimeo.com/jamesrampton"


[[social]]
name = "RSS"
icon = "rss"
order = 6
url = "/feed.xml"
