description = "The personal website and blog of James Rampton"
noSEO = false

[[social]]
    name = "Vimeo"
    icon = "vimeo"
    order = 1
    url = "//vimeo.com/jamesrampton"

[[social]]
    name = "Flickr"
    icon = "flickr"
    order = 2
    url = "//flickr.com/jamesrampton"

[[social]]
    name = "Bandcamp"
    icon = "bandcamp"
    order = 3
    url = "//jamesrampton.bandcamp.com"
