baseURL = "https://www.jamesrampton.uk/"
languageCode = "en-us"
title = "James Rampton"

[markup]
    [markup.highlight]
        noClasses = false

[imaging.exif]
includeFields = ".*"

[params]
    description = "The personal website and blog of James Rampton"

[[params.social]]
    name = "Vimeo"
    icon = "vimeo"
    order = 1
    url = "//vimeo.com/jamesrampton"

[[params.social]]
    name = "Soundcloud"
    icon = "soundcloud"
    order = 2
    url = "//soundcloud.com/jamesrampton"

[[params.social]]
    name = "Bandcamp"
    icon = "bandcamp"
    order = 3
    url = "//jamesrampton.bandcamp.com"
