baseURL = "https://www.jamesrampton.uk/"
languageCode = "en-us"
title = "James Rampton"
theme = "jimothy"
[params]
    avatar = "images/logo.svg"
    page_not_found_image = "images/broken_logo.svg"
    fontawesomeKey = "ea942b1dc0"
[params.social]
    networks = [
        ["vimeo", "//vimeo.com/jamesrampton"],
        ["soundcloud", "//soundcloud.com/jamesrampton"],
        ["bandcamp", "//jamesrampton.bandcamp.com"]
    ]