baseURL = "https://www.jamesrampton.uk/"
languageCode = "en-us"
title = "James Rampton"

[markup]
    [markup.highlight]
        noClasses = false

[imaging.exif]
includeFields = ".*"

[ menu ]
[[ menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1

[params]
    description = "The personal website and blog of James Rampton"

[[params.social]]
    name = "Vimeo"
    icon = "vimeo"
    order = 1
    url = "//vimeo.com/jamesrampton"

[[params.social]]
    name = "Flickr"
    icon = "flickr"
    order = 2
    url = "//flickr.com/jamesrampton"

[[params.social]]
    name = "Bandcamp"
    icon = "bandcamp"
    order = 3
    url = "//jamesrampton.bandcamp.com"
