baseURL = "https://www.jamesrampton.uk/"
languageCode = "en-us"
title = "James Rampton"
theme = "jimothy"

[params]
    avatar = "images/logo.svg?v=2"
    page_not_found_image = "images/broken_logo.svg?v=2"

[[params.social]]
    name = "Vimeo"
    icon = "vimeo"
    order = 1
    url = "//vimeo.com/jamesrampton"

[[params.social]]
    name = "Soundcloud"
    icon = "soundcloud"
    order = 2
    url = "//soundcloud.com/jamesrampton"

[[params.social]]
    name = "Bandcamp"
    icon = "bandcamp"
    order = 3
    url = "//jamesrampton.bandcamp.com"
