baseURL = "https://www.jamesrampton.uk"
languageCode = "en-us"
title = "James Rampton"
theme = "jimothy"
[params]
    avatar = "images/logo.svg"
    page_not_found_image = "images/broken_logo.svg"
    fontawesomeKey = "ea942b1dc0"
    vimeoLink = "https://vimeo.com/jamesrampton"
    soundcloudLink = "https://soundcloud.com/jamesrampton"
    bandcampLink = "https://jamesrampton.bandcamp.com"
