[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.85.0"

[[ redirects ]]
  from = "/js/script.js"
  to = "https://plausible.io/js/pplausible.outbound-links.js"
  status = 200

[[ redirects ]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202

