version: 2

jobs:
  deploy-production:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST ". ~/update_jamesrampton_web"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: master # only deploy on the master branch
